# Generated by Django 3.2.17 on 2023-03-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230304_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='img',
        ),
    ]
