# Generated by Django 3.2.17 on 2023-03-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
